version: '3'
services:
  redis:
    image: "redis:latest"
    ports:
      - "${REDIS_DOCKER_PORT}:6379"
    networks:
      - net

  postgres:
    image: "postgres:latest"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - ./scripts/sql:/docker-entrypoint-initdb.d
    ports:
      - "${POSTGRES_DOCKER_PORT}:5432"
    networks:
      - net

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_DOCKER_PORT}:${APP_DOCKER_PORT}"
    depends_on:
      - postgres
      - redis
    networks:
      - net

  nginx:
    image: "nginx:latest"
    ports:
      - "81:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - net

networks:
  net:
    driver: bridge