version: "3.9"
services:
  app:
    build:
      context: .
      args:
        - BUILDER_IMAGE=myproject_builder:latest
    expose:
      - "8081"
      - "6379"
      - "5432"
    env_file:
      - .env
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    restart: always
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    env_file:
      - .env
volumes:
  postgres_volume: